version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "pip"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check the pip registry for updates every day (weekdays)
    schedule:
      interval: "weekly"

    # Allow up to 5 open pull requests for pip dependencies
    open-pull-requests-limit: 5
