name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Action Security
      run: git config --global url."https://${{ secrets.PA_TOKEN }}:x-oauth-basic@github.com".insteadOf https://github.com
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose